DUOS-1172[risk=no]UI: State Unselectable with no message explaining why
DataBiosphere/duos-ui pull request #1014
Opened 2021-04-13 17:55 UTC by raejohanek

SCOPE:
- updated state validation check 
- leave state box enabled when no country is selected, only disable when a non US country is selected
- fix tooltip for isPi
- add tooltip for state

ADDRESSES:
https://broadworkbench.atlassian.net/browse/DUOS-1172

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] PR is labeled with a Jira ticket number and includes a link to the ticket
- [ ] PR is labeled with a security risk modifier [no, low, medium, high] 
- [ ] PR describes scope of changes

In all cases:

- [ ] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [ ] Get PO sign-off for all non-trivial UI or workflow changes
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2021-04-13 17:56 UTC, raejohanek commented on src/pages/ResearcherProfile.js
> +    //clear out state field if the user selects
before this code block was here when you would chose another country the state box would be disabled but still show the state value that was in it before

2021-04-14 13:08 UTC, rushtong requested changes
See comment inline. Ignore the failing cloud build check, we'll get that removed at some point.

2021-04-14 13:08 UTC, rushtong commented on src/pages/ResearcherProfile.js
> +    const stateSelected = (!isNil(value) || !isEmpty(value));
This is reporting valid even if I unselect the state option so validation is failing here.

2021-04-15 13:00 UTC, rushtong approved these changes
Thank you for the changes, works well 👍🏽

2021-04-15 13:56 UTC, merged