DUOS-1238[risk=no]Add DAR view link to new DAC Chair Console 'unopened' DARs + text desc.
DataBiosphere/duos-ui pull request #1092
Opened 2021-05-13 15:45 UTC by raejohanek

SCOPE:
- Add links to review results page on non-open election statuses  (Unreviewed, Approved, Denied, Canceled) for the chair console
- Change -- to 'unreviewed' status for dars with no elections

ADDRESSES:
https://broadworkbench.atlassian.net/browse/DUOS-1238

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] PR is labeled with a Jira ticket number and includes a link to the ticket
- [ ] PR is labeled with a security risk modifier [no, low, medium, high] 
- [ ] PR describes scope of changes

In all cases:

- [ ] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [ ] Get PO sign-off for all non-trivial UI or workflow changes
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2021-05-13 17:38 UTC, JVThomas commented
`review_results` will always error for unreviewed DARs because the `Match.findMatch()` call needs an election id which they don't have, so you'll need to figure out how to make the Match call when needed.

![Kapture 2021-05-13 at 13 28 47](https://user-images.githubusercontent.com/6664778/118162979-651eb900-b3ef-11eb-9016-d22669fd3c01.gif)

2021-05-13 17:49 UTC, raejohanek commented on src/pages/ReviewResults.js
> +      }
by adding the null check for accessElection this code works for unreviewed dars too

2021-05-13 18:12 UTC, rushtong requested changes
I think this PR goes a little further than the ticket requires. The ticket doesn't specifically request that "Unreviewed" link to the Review Results page, only that the string "- -" be replaced with "Unreviewed". I can see the logic in taking that step, but I think it might be scope creep. Additionally, if we do increase the scope to what this PR is trying to do, then ReviewResults will need some enhanced logic because when it's unreviewed, it's trying to get an election for a DAR that doesn't have one and there is a 404 in the network panel that we shouldn't be making.

2021-05-13 18:12 UTC, rushtong commented on src/Routes.js
> +      rolesAllowed={[USER_ROLES.admin, USER_ROLES.alumni, USER_ROLES.chairperson]} />
I think this should be open to members as well, but we might not have a code path for that yet.

2021-05-13 18:14 UTC, raejohanek commented
> I think this PR goes a little further than the ticket requires. The ticket doesn't specifically request that "Unreviewed" link to the Review Results page, only that the string "- -" be replaced with "Unreviewed". I can see the logic in taking that step, but I think it might be scope creep. Additionally, if we do increase the scope to what this PR is trying to do, then ReviewResults will need some enhanced logic because when it's unreviewed, it's trying to get an election for a DAR that doesn't have one and there is a 404 in the network panel that we shouldn't be making.

I just talked to Jonathan about this ticket this morning and confirmed that this is what we want to do. I need to make the changes to the ticket to reflect that because it was a bit unclear.

2021-05-13 18:40 UTC, raejohanek commented
> > I think this PR goes a little further than the ticket requires. The ticket doesn't specifically request that "Unreviewed" link to the Review Results page, only that the string "- -" be replaced with "Unreviewed". I can see the logic in taking that step, but I think it might be scope creep. Additionally, if we do increase the scope to what this PR is trying to do, then ReviewResults will need some enhanced logic because when it's unreviewed, it's trying to get an election for a DAR that doesn't have one and there is a 404 in the network panel that we shouldn't be making.
> 
> I just talked to Jonathan about this ticket this morning and confirmed that this is what we want to do. I need to make the changes to the ticket to reflect that because it was a bit unclear. I'll take a look at the logic and try to simplify things for the unreviewed case

So I just added an optional param to pass to the review results page if the status is unreviewed, then if that optional param is present in the review results page it does not make the call to find the election

2021-05-17 14:54 UTC, rushtong commented on src/pages/ReviewResults.js
> +  const status = props.match.params.referenceId;
This looks like a copy paste error. Shouldn't it be looking for the `status` param?

2021-05-17 14:56 UTC, rushtong commented on src/pages/ReviewResults.js
>      }
If we know that `Unreviewed` will have no election, why are we making the query at all? Could you wrap the call with `if (status !== 'Unreviewed')` ?

2021-05-17 14:57 UTC, rushtong requested changes
Looking better. See comments inline.

2021-05-17 17:21 UTC, rushtong approved these changes
Thanks for the changes. As fallout from this, I created https://broadworkbench.atlassian.net/browse/DUOS-1265.

2021-05-17 18:23 UTC, merged