DUOS-1316[risk=no]Beautify NIH IC Webform page UI
DataBiosphere/duos-ui pull request #1133
Opened 2021-06-15 21:25 UTC by raejohanek

SCOPE:
- fix styling, make consistent coloring, add icon
- Add states so radio buttons and checkboxes are functional
- Add dropdown options so menus are functional
- Implement the ability to create multiple consent groups and render all created groups
- Update question content per Jonathan's guidelines
- Fix dataset registration agreement download button
ADDRESSES:
https://broadworkbench.atlassian.net/browse/DUOS-1316

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2021-06-16 16:26 UTC, rushtong commented
The era commons link is not working, I think because `location` is null and never defined.

![Screen Shot 2021-06-16 at 12 25 40 PM](https://user-images.githubusercontent.com/116679/122257403-faedae00-ce9d-11eb-9ce9-6f25ded6ea5d.png)

2021-06-16 16:29 UTC, rushtong commented
The `nih_ic_webform` seems to be behind the login now. In the original, that is not the case. I don't see this in the ticket, is that intentional?

2021-06-16 16:35 UTC, raejohanek commented
> The `nih_ic_webform` seems to be behind the login now. In the original, that is not the case. I don't see this in the ticket, is that intentional?

No, good catch, that is not intentional, how do I change it back? I did not change anything about Routes or permissions

2021-06-16 16:38 UTC, raejohanek commented
> The era commons link is not working, I think because `location` is null and never defined.


Yeah, Jonathan said it does not need to be functional, I thought this was redirecting to the fake era login page, if I can get that working do you think that is a good approach?

2021-06-16 16:47 UTC, rushtong commented
> > The nih_ic_webform seems to be behind the login now. In the original, that is not the case. I don't see this in the ticket, is that intentional?

> No, good catch, that is not intentional, how do I change it back? I did not change anything about Routes or permissions

I don't see how this is happening in the code, but it does happen for me locally. Will continue to look into it more as I review.

2021-06-16 16:48 UTC, rushtong commented
> > The era commons link is not working, I think because location is null and never defined.

> Yeah, Jonathan said it does not need to be functional, I thought this was redirecting to the fake era login page, if I can get that working do you think that is a good approach?

On dev/staging, the link it points to is a mock version of era commons login. On prod, it is a real one. To make it work, you need to define the `location` variable which is where the auth redirect tries to send the user back to. In this case, it's the web form page.

2021-06-16 16:59 UTC, rushtong commented
I see why it is now behind the login. Adding the era commons component did this. On that component, it checks the user info: 

```
  componentDidMount = async () => {
    if (this.props.location !== undefined && this.props.location.search !== '') {
      await this.authenticateAsNIHFCUser(this.props.location.search);
    } else {
      await this.getUserInfo();
    }
  };
```

And since that returns a 401 on the /api/me` call, the application catches that and returns you back to the home page. We can't use the era commons component on an un-authed page since it needs access to the authed user.

2021-06-16 17:05 UTC, raejohanek commented
> I see why it is now behind the login. Adding the era commons component did this. On that component, it checks the user info:
> 
> ```
>   componentDidMount = async () => {
>     if (this.props.location !== undefined && this.props.location.search !== '') {
>       await this.authenticateAsNIHFCUser(this.props.location.search);
>     } else {
>       await this.getUserInfo();
>     }
>   };
> ```
> 
> And since that returns a 401 on the /api/me` call, the application catches that and returns you back to the home page. We can't use the era commons component on an un-authed page since it needs access to the authed user.

Okay that makes sense, Thanks!   I think we can probably just remove the button since its not functional anyways but I'll ask Jonathan if he would rather have the page un-authed or have the eraCommons button on it as of now

2021-06-16 17:07 UTC, rushtong requested changes
Aside from the era commons issue, the page looks good and seems to work as intended.

2021-06-16 17:07 UTC, rushtong commented on src/pages/NIHicWebform.js
> +                  })
This component requires an auth-ed user to be logged in so any non-auth-ed user will be redirected back to the home page. If this page needs to be public, then we need to replace this with a free text field for the user to enter their era commons id.

2021-06-16 17:42 UTC, raejohanek commented
> Aside from the era commons issue, the page looks good and seems to work as intended.

Okay, I checked with Jonathan to see what he thought and per his suggestion, I replaced the eraCommons button with another button that does nothing

2021-06-17 18:09 UTC, JVThomas requested changes
One bug, but other than that the page looks to work as expected. Radio buttons in the gif below don't function properly. Once selected they can never be unselected.

![Kapture 2021-06-17 at 14 06 25](https://user-images.githubusercontent.com/6664778/122450848-7a01e580-cf75-11eb-9b73-0813d6a2ed0f.gif)

2021-06-17 18:17 UTC, raejohanek commented
> One bug, but other than that the page looks to work as expected. Radio buttons in the gif below don't function properly. Once selected they can never be unselected.

Good catch thank you, I just fixed that bug and pushed the changes

2021-06-17 19:44 UTC, JVThomas approved these changes
Bug is fixed, consent group list updates as expected, buttons and text fields update as expected.

2021-06-17 20:03 UTC, rushtong approved these changes
👍🏽

2021-06-17 20:04 UTC, merged