DUOS-1336[risk=no]UI: Consolidate Console Design
DataBiosphere/duos-ui pull request #1193
Opened 2021-07-23 15:32 UTC by raejohanek

SCOPE: 
- create dropdown menu of consoles
- make links into reusable constants, and add logic for when to render
- remove sublist (manage Dars and manae Dacs) when in the 'your consoles' dropdown  and render them in the main list, slightly indented

ADDRESSES:
- https://broadworkbench.atlassian.net/browse/DUOS-1336

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2021-07-26 12:24 UTC, JVThomas requested changes, later dismissed
Make the `DAC Chair Console` text bolder to make it stick out as a list header and also to show that it's different from the other options (which are links).
<img width="374" alt="Screen Shot 2021-07-26 at 8 19 13 AM" src="https://user-images.githubusercontent.com/6664778/126987847-2e4248b1-6c41-4bf5-848a-45630fa671d2.png">

2021-07-26 13:55 UTC, JVThomas commented on src/components/DuosHeader.js
> +        span({style: { color: '#00609f', fontSize: '12px', fontWeight: '500', padding: '10px 15px'}}, ['DAC Chair Console'])
Use a font-weight that's heavier than 500 (600 is considered semi-bold, 800 is bold) for a more noticeable effect.

2021-07-26 14:40 UTC, rushtong commented on src/components/DuosHeader.js
> +    };
This can definitely be a lot simpler. The `currentUser` has a list of roles on it ... we just need to count the distinct rolenames from that list.

2021-07-26 14:49 UTC, rushtong commented on src/components/DuosHeader.js
> +    };
Here's how to get all of the distinct role names ... 

```
import { isNil, uniq, map } from 'lodash/fp';
...
      const roleNames = uniq(map("name")(currentUser.roles));
      console.log(JSON.stringify(roleNames));
```
That gives my superadmin user the following on dev:
```
["Alumni","Admin","Researcher","DataOwner","Chairperson","SigningOfficial"]
```

2021-07-26 14:53 UTC, rushtong commented
It looks good, works well, but I do have a couple of ideas that might make it better.
* The "DAC Chair Console" header looks clickable. Not sure how to make it not look that way, maybe removing the blue color from the text and bolding it a little more
* Clicking on the header when it's not a link closes the menu. Not sure how to resolve that problem. PR should not be held up on that minor point though.

2021-07-26 14:54 UTC, rushtong requested changes
See comments inline. Looks very good!

2021-07-26 16:32 UTC, raejohanek commented
> * The "DAC Chair Console" header looks clickable. Not sure how to make it not look that way, maybe removing the blue color from the text and bolding it a little more
> * Clicking on the header when it's not a link closes the menu. Not sure how to resolve that problem. PR should not be held up on that minor point though.

I'm not sure how to resolve that second point either, but I made the text bolder and black, I think it looks better. Do you think it would be helpful if we changed the text to something like DAC Chair Console Options instead of just DAC Chair Console?

2021-07-27 12:33 UTC, rushtong commented
@raejohanek 
> Do you think it would be helpful if we changed the text to something like DAC Chair Console Options instead of just DAC Chair Console?

I think the current text is better.

2021-07-27 12:36 UTC, rushtong approved these changes
Looks great!

2021-07-27 13:22 UTC, merged