[DUOS-1452][risk=no] Dataset Catalog Refactor
DataBiosphere/duos-ui pull request #1268
Opened 2021-09-16 16:03 UTC by rushtong

## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1452

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2021-09-24 12:20 UTC, JVThomas requested changes
I left some comments explaining the comments you've left on the selectAll and singleSelect methods. You don't have to implement them since the current functionality works.

The code works as expected, the issue is a matter of expected functionality. When you click the select all button, only the items on the current page is selected. If a user wants to select all the items on a second page, they won't be able to do so. If you hit the button to unselect, ALL checkboxes are unselected.

![Kapture 2021-09-24 at 08 13 37](https://user-images.githubusercontent.com/6664778/134673101-69cb809f-dc40-4467-bdb1-d55304688b03.gif)


A good example of select all functionality is on gmail. When you hit the button, the select all/unselect all button are only applied to the current page. So if you select all on one page and then turn to an untouched page, the Check All button switches back to an unselected state. 

Gmail has additional states for partial selects, but we can keep it simple. If all are selected, make the Select All button checked. If not, show it as unchecked.

2021-09-24 12:20 UTC, JVThomas commented on src/pages/DatasetCatalog.js
> +    const selectedDatasets = forEach(row => {
`forEach` returns the original array's reference. React does state updates on value changes, but if the saved value is the array reference, then changing the array's contents triggers nothing since the reference value is unchanged.

`map` should be enough to trigger the state change since it performs the content manipulation on a new array.

2021-09-24 12:20 UTC, JVThomas commented on src/pages/DatasetCatalog.js
> +    setDatasetList(selectedDatasets);
Technically the arrays are the same here too, but since `allChecked` had a state change the component will re-render regardless. So it's working out but not for the expected reason.

2021-09-24 12:20 UTC, JVThomas commented on src/pages/DatasetCatalog.js
> +    const checked = e.target.checked;
To be safe, have checked fallback on `false` to avoid `undefined` assignments (which would cause checkboxes to error out since it's expecting a boolean).

2021-09-24 12:20 UTC, JVThomas commented on src/pages/DatasetCatalog.js
> +          row.checked = checked;
Same checked comment as the previous method.

2021-09-24 12:20 UTC, JVThomas commented on src/pages/DatasetCatalog.js
> +    setDatasetList([...selectedDatasets]);
If you're using `map` then you won't need to use the spread operator to create a new array.

2021-09-24 12:20 UTC, JVThomas commented on src/pages/DatasetCatalog.js
> +                    // console.log(JSON.stringify(dataset.active));
Comment cleanup here

2021-09-24 12:20 UTC, JVThomas commented on src/pages/DatasetCatalog.js
> +        ConfirmationDialog({
Doesn't need to be addressed now (should be a different ticket), but this can easily be one modal that updates the action method and text based on the button clicked instead of having four different versions of the same modal.

2021-09-24 13:49 UTC, rushtong commented
@JVThomas - great feedback all around, will implement!

2021-09-27 14:39 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +    const selectedDatasets = forEach(row => {
Done

2021-09-27 14:39 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +    setDatasetList(selectedDatasets);
Done

2021-09-27 14:40 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +    const checked = e.target.checked;
Done

2021-09-27 14:40 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +          row.checked = checked;
Since `checked` is now a safe check, this should now be safe as well.

2021-09-27 14:40 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +    setDatasetList([...selectedDatasets]);
Done

2021-09-27 14:41 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +                    // console.log(JSON.stringify(dataset.active));
Done

2021-09-27 14:41 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +        ConfirmationDialog({
Agreed, this can be cleaned up. Will file a ticket for this.

2021-09-28 12:31 UTC, rushtong commented on src/pages/DatasetCatalog.js
> +        ConfirmationDialog({
Created https://broadworkbench.atlassian.net/browse/DUOS-1460 to handle this concern.

2021-09-29 14:31 UTC, JVThomas approved these changes
Code looks good, the table buttons are working as expected and inaccessible datasets are no longer selectable.

2021-09-29 18:06 UTC, merged