DUOS-1642[risk=no] UI dataset required sub section in data use bucket
DataBiosphere/duos-ui pull request #1482
Opened 2022-03-23 18:38 UTC by shaemarks

[Link to Jira ticket](https://broadworkbench.atlassian.net/browse/DUOS-1642)
Summary of changes: 

- Filter datasets to only include those that belong to both the given bucket and given list of datasets for this dac
- When collapsed, display the first 5 datasets and a link to expand
- When expanded, display all datasets and a link to collapse 

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-03-23 18:52 UTC, shaemarks commented
To test locally, I added the code below to `DarCollectionReview.js`  and went to `http://localhost:3000/dar_collection/{any collection ID}`. The dataSetIds listed under `bucket.elections` correspond to the datasets for the Dac with dacID 3 (should be displayed), but other ids can be added for when the bucket and dar datasets do not match.

```
 const [dacDatasets, setDacDatasets] = useState([]);


 const dacDatasets = await DAC.datasets(3);
 setDacDatasets(dacDatasets);


   h(DatasetsRequestedPanel, {
        bucket: {
          elections: [[
            {dataSetId: 1398},
            {dataSetId: 1399},
            {dataSetId: 459},
            {dataSetId: 1403},
            {dataSetId: 384},
            {dataSetId: 1396},
            {dataSetId: 1397},
            {dataSetId: 390},
          ]]
        },
        dacDatasets,
        isLoading
      })
```

2022-03-25 13:08 UTC, rushtong requested changes
Very minor comments, but otherwise, code looks very good!

2022-03-25 13:08 UTC, rushtong commented on cypress/component/ResearchProposalVoteSlab/datasets_requested.spec.js
> +}
nit: missing semi-colons

2022-03-25 13:08 UTC, rushtong commented on cypress/component/ResearchProposalVoteSlab/datasets_requested.spec.js
> +]
nit: same here

2022-03-25 13:08 UTC, rushtong commented on src/components/collection_voting_slab/DatasetsRequestedPanel.js
> +  };
The dataset's name is just `dataset.name`

2022-03-25 13:08 UTC, rushtong commented on src/components/collection_voting_slab/DatasetsRequestedPanel.js
> +  };
The ID we show on the catalog page is labeled `dataset.datasetIdentifier` in the returned dataset we have in the DAR Collection

2022-03-25 14:20 UTC, shaemarks commented on src/components/collection_voting_slab/DatasetsRequestedPanel.js
> +  };
I see `dataset.name` and `dataset.datasetIdentifier` in the datasets within a whole collection, but I'm not seeing the same properties within the datasets retrieved from the `/api/dac/{dacId}/datasets` endpoint or the `processedBuckets`

2022-03-28 10:01 UTC, rushtong commented on src/components/collection_voting_slab/DatasetsRequestedPanel.js
> +  };
In both cases, we should have access to the database id of the dataset - is that not enough to do a comparison? Do we need to add anything to either endpoint to accomplish what you're trying to do?

2022-03-28 12:15 UTC, shaemarks commented on src/components/collection_voting_slab/DatasetsRequestedPanel.js
> +  };
We can compare the dataset ids from the endpoint and `processedBuckets` to filter which datasets we need, and then compare those matching dataset ids against the collection datasets to get the needed properties. The other option would be to alter  `/api/dac/{dacId}/datasets` to include those properties.

2022-03-30 13:44 UTC, quazi-h approved these changes
The new component code for a Datasets Requested sub-section looks good to me

2022-03-30 14:10 UTC, rushtong commented on src/components/collection_voting_slab/DatasetsRequestedPanel.js
> +      return includes(dataset.datasetId)(datasetsForDacInBucket);
The dataset id property on the dataset is weirdly capitalized due to history ... this line should be:
```suggestion
      return includes(dataset.dataSetId)(datasetsForDacInBucket);
```

2022-03-30 14:11 UTC, rushtong requested changes
Code looks good! One more small fix, then 👍🏽

2022-03-30 14:13 UTC, rushtong commented on src/components/collection_voting_slab/DatasetsRequestedPanel.js
> +      return includes(dataset.datasetId)(datasetsForDacInBucket);
Just an FYI for testing purposes, I added this component to the DarCollectionReview page and viewed collection id 190 on dev:
```
      h(DatasetsRequestedPanel, {
        bucketDatasetIds: [1250, 449],
        dacDatasetIds: [1250],
        collectionDatasets: collection.datasets,
        isLoading
      }),
```
Fiddling with the bucketDatasetIds and dacDatasetIds shows me the results I was expecting to see.

2022-03-30 14:17 UTC, rushtong approved these changes
Thanks for the changes!

2022-03-30 15:04 UTC, merged