[DUOS-1806][risk=no] fix actions on new researcher console
DataBiosphere/duos-ui pull request #1559
Opened 2022-05-17 15:42 UTC by shaemarks

[Link to Jira ticket](https://broadworkbench.atlassian.net/browse/DUOS-1806)
Summary of changes:
- Use `ResearcherActions` instead of previous action function for `new_researcher_console`
- Remove collection from `DarCollectionTable` when resubmit button is clicked 
- Adjust styling of buttons to be closer to `DarCollectionTable` on other consoles
- Link review button to dar application page with disabled fields 
- Adjust logic for showing researcher action buttons: 
   - cancel button is visible when there a collection has no elections on it and not all dars are canceled
   - resubmit button is visible when all dars are canceled

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-05-18 10:50 UTC, rushtong commented
Style request, can we align the buttons to the left? The current centering makes it look tree-like:

<img width="302" alt="Screen Shot 2022-05-18 at 6 44 15 AM" src="https://user-images.githubusercontent.com/116679/169022127-421296b0-a3a2-4977-9ff3-908b466c8f82.png">

2022-05-18 10:50 UTC, rushtong commented
Wording request - can we align the modal language with the button language when clicking "Revise"?

<img width="1513" alt="Screen Shot 2022-05-18 at 6 44 47 AM" src="https://user-images.githubusercontent.com/116679/169022349-17d6ae00-7fc4-451f-95cd-f4e8d18f68dd.png">

2022-05-18 10:52 UTC, rushtong commented
The one example I have for revise (DAR-138) is throwing a 500 on the back end ... need to dig into that to be sure there isn't something wrong with the API call from the front end. It's likely fine, problem is 99% likely an API issue.

2022-05-18 11:21 UTC, rushtong commented
> The one example I have for revise (DAR-138) is throwing a 500 on the back end ... need to dig into that to be sure there isn't something wrong with the API call from the front end. It's likely fine, problem is 99% likely an API issue.

Submitted https://github.com/DataBiosphere/consent/pull/1579 to get past the 500 error I saw. The revise feature works correctly with these PRs in tandem.

2022-05-18 11:39 UTC, rushtong requested changes
See comments inline. Functionality works great - I just think we need a couple minor visual updates.

2022-05-18 11:39 UTC, rushtong commented on src/components/dar_collection_table/DarCollectionTable.js
>    //  - depends, if cancel and resubmit are locked behind modals then I only would have to pass in openCollection (only for admin and chair)
Are these comments still relevant? I'm not sure I understand what they're trying to get at here.

2022-05-18 11:39 UTC, rushtong commented on src/pages/NewResearcherConsole.js
> +      });
nit: language. Can we refer to collections as Data Access Requests instead?

2022-05-18 14:41 UTC, shaemarks commented
> Wording request - can we align the modal language with the button language when clicking "Revise"?
> 
> <img alt="Screen Shot 2022-05-18 at 6 44 47 AM" width="1513" src="https://user-images.githubusercontent.com/116679/169022349-17d6ae00-7fc4-451f-95cd-f4e8d18f68dd.png">

Should just the user-facing wording on the modal change, or should I refactor so that this action is consistently referred to as "revise" instead of "resubmit" in the code?

2022-05-18 15:05 UTC, shaemarks commented on src/pages/NewResearcherConsole.js
> +      });
I replaced "collection" with "Data Access Request" for messages similar to the ones above. The current success messages say something along the lines of "Revising collection DAR-123". For these messages, would be it best to: 
1) keep as "Revising collection DAR-123"
2) change to "Revising Data Access Request DAR-123"
3) change to "Revising DAR-123"

2022-05-18 15:53 UTC, rushtong commented on src/pages/NewResearcherConsole.js
> +      });
Option 2 looks best to me

2022-05-18 15:54 UTC, rushtong commented
> > Wording request - can we align the modal language with the button language when clicking "Revise"?
> > <img alt="Screen Shot 2022-05-18 at 6 44 47 AM" width="1513" src="https://user-images.githubusercontent.com/116679/169022349-17d6ae00-7fc4-451f-95cd-f4e8d18f68dd.png">
> 
> Should just the user-facing wording on the modal change, or should I refactor so that this action is consistently referred to as "revise" instead of "resubmit" in the code?

`should I refactor so that this action is consistently referred to as "revise" instead of "resubmit"` seems like the best choice to me.

2022-05-19 11:40 UTC, quazi-broad approved these changes
Functionality is working as expected - DARs with complete elections only have the "Review" action available instead of "Cancel". Agree with Greg's suggestions on visual changes.

2022-05-19 12:55 UTC, rushtong approved these changes
Thank you for the changes 👍🏽

2022-05-19 12:56 UTC, merged