[DUOS-1740][risk=no] Single Quote Rule
DataBiosphere/duos-ui pull request #1561
Opened 2022-05-18 11:45 UTC by rushtong

## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1740

Add a single quote rule to eslint

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-05-18 17:49 UTC, shaemarks approved these changes
When using double quotes instead of single quotes, the text was highlighted with a warning and had a shortcut to swap with single quotes

2022-05-23 17:50 UTC, JVThomas requested changes

2022-05-23 17:50 UTC, JVThomas commented on .eslintrc
> +    "quotes": ["warn", "single"], // Checks for single quote usage where possible
Change it to `"quotes": ["warn", "single", {"avoidEscape": true}]`. It's okay to use double quotes if the string has  apostrophes in it, otherwise you have to manually escape each apostrophe in the string.

2022-05-23 19:58 UTC, rushtong commented on .eslintrc
> +    "quotes": ["warn", "single"], // Checks for single quote usage where possible
Thank you, feedback applied, PTAL

2022-05-23 20:01 UTC, JVThomas approved these changes

2022-05-23 20:06 UTC, merged