DUOS-1822[risk=med] Enable MDV for Prod, Updated Env Conditionals
DataBiosphere/duos-ui pull request #1668
Opened 2022-07-11 21:26 UTC by quazi-h

[DUOS-1822](https://broadworkbench.atlassian.net/browse/DUOS-1822)

- Update all nav links in routes to apply to all environments.
- Removed conditional logic that considers the environment for routes to the console pages.
- Updated the app to exclusively use the new DUOS header.
- Updated links in the new and old header code to point to the new consoles.
- Updated utils to point to new consoles.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-07-11 21:28 UTC, quazi-broad commented
Open Questions:
- Should my changes include switching over to the new header and nav bar for prod?
- Unsure if I replaced the isRendered arguments correctly in SigningOfficialDataSubmitters and SigningOfficialConsole.
- Wasn't sure where to add tests/which tests to update.
- auth.cy.js is currently failing:
```
  1) Authentication
       Background Sign-in Admin:
     Error: Must pass in a JSON object containing the Google auth settings.
      at GoogleAuth.fromJSON (http://localhost:3000/__cypress/tests?p=cypress/support/e2e.js:48698:19)
      at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/support/e2e.js:41585:23)
```

2022-07-12 10:23 UTC, rushtong commented
> Open Questions:
> 
> * Should my changes include switching over to the new header and nav bar for prod?

No, this should not cover the navigation. That is covered in https://broadworkbench.atlassian.net/browse/DUOS-1887. The new navigation is dependent on MDV, so this has to go first.

2022-07-12 10:38 UTC, rushtong commented
> Open Questions:
> 
> * Unsure if I replaced the isRendered arguments correctly in SigningOfficialDataSubmitters and SigningOfficialConsole.

Signing official changes are related to navigation, not MDV, so please revert those.

2022-07-12 10:46 UTC, rushtong requested changes
This PR mixes some navigation changes in with MDV, so let's try to split them back out so they can be separately addressed. One issue I see is that we've lost some CSS for the old header - likely in a previous PR. Once I back out the new header nav, the UI looks like the attached screenshot. We'll need to get that back before this goes forward.

<img width="1424" alt="Screen Shot 2022-07-12 at 6 44 07 AM" src="https://user-images.githubusercontent.com/116679/178473079-a0660031-086f-4452-9de5-5d0bef16d050.png">

2022-07-12 10:46 UTC, rushtong commented on src/App.js
> +          h(DuosHeader, { onSignOut: signOut }),
These changes are related to DUOS-1887 and outside of the scope of the linked ticket.

2022-07-12 10:46 UTC, rushtong commented on src/pages/AdminConsole.js
> +                isRendered: this.state.showAddUserModal,
This div should be removed altogether as it is referencing an outdated page, Manage DARs.

2022-07-12 10:46 UTC, rushtong commented on src/pages/AdminConsole.js
> +                isRendered: this.state.showAddUserModal,
This div should always be enabled now. It is essentially a replacement for the previous div.

2022-07-12 10:46 UTC, rushtong commented on src/pages/AdminConsole.js
> +                isRendered: this.state.showAddUserModal,
This div can go away altogether, it is replaced by the div on line 179

2022-07-12 21:45 UTC, quazi-broad commented on src/App.js
> +          h(DuosHeader, { onSignOut: signOut }),
Backed these changes out.

2022-07-13 12:51 UTC, rushtong approved these changes
Once https://github.com/DataBiosphere/duos-ui/pull/1671 lands, pull those changes into this branch and we should be good 👍🏽

2022-07-13 16:10 UTC, JVThomas approved these changes

2022-07-13 16:37 UTC, merged