Moving configs to dotenv
DataBiosphere/duos-ui pull request #167
Opened 2019-06-14 12:36 UTC by dags

Configuration moved to ENV variables, read by dotenv.

2019-06-14 13:01 UTC, rushtong commented
This changes how we would execute the deploys to kubernetes. We will need one of two things:
1. `.env` files and changes to the circleci yaml to move those around to the right places
2. A separate job/process (jenkins?) that generates a configmap deploy to the clusters so the `env` arguments are populated correctly.

I suggest we close this PR for now so we can write up a tech-doc (along with jira tickets) on how to convert the current deploys.

2019-06-17 19:00 UTC, tadeork approved these changes

2019-06-18 13:06 UTC, rushtong requested changes
As mentioned in comments, this will break the current deployment. Can we close this, but keep the branch around, and work on a technical design that covers both this subject and the deployment?

2019-06-27 17:15 UTC, rushtong commented
Closing until we can revisit the overall process.

2019-06-27 17:15 UTC, closed without merging