[DUOS-1896][risk=no] Ensure UserProperties deprecation does not break frontend
DataBiosphere/duos-ui pull request #1683
Opened 2022-07-18 17:22 UTC by connorlbark

## Partially addresses 

https://broadworkbench.atlassian.net/browse/DUOS-1896

Basic frontend changes to ensure that https://github.com/DataBiosphere/consent/pull/1650 does not break the UI.

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-07-19 11:19 UTC, rushtong requested changes
Have a look at `UserProperties` in `utils.js`. There are a lot of usages of some outdated properties. For example, `CITY` is used in `AppSummary.js`, but when it is passed to a subcomponent (`ApplicantInfo`), it is not used anywhere. It would be great if we could clean up unused constants in `UserProperties` for this PR.

2022-07-19 11:19 UTC, rushtong commented on src/components/ApplicationDownloadLink.js
> +  const location = (researcherProps.city && researcherProps.state ? (researcherProps.city).concat(', ').concat(researcherProps.state) : '');
We should remove this altogether, along with the location block on line 209

2022-07-19 11:19 UTC, rushtong commented on src/libs/utils.js
> +  return institutionPresent;
This can be inlined and remove `institutionPresent` as a temp var.
```
return !isNil(institutionId);
```

2022-07-19 17:28 UTC, connorlbark commented
> Have a look at `UserProperties` in `utils.js`. There are a lot of usages of some outdated properties. For example, `CITY` is used in `AppSummary.js`, but when it is passed to a subcomponent (`ApplicantInfo`), it is not used anywhere. It would be great if we could clean up unused constants in `UserProperties` for this PR.

ohh okay i think i misinterpreted you when we talked in standup yesterday - i can remove those references and work on updating it all!

2022-07-19 18:43 UTC, connorlbark commented
i believe that i removed all usages of deprecated user properties EXCEPT for the usages on the dar application page; I can go ahead and do that, too, but I wasn't sure if that was in the scope of this PR.

2022-07-21 13:08 UTC, rushtong commented on src/components/ApplicationDownloadLink.js
> -          }),
This block is something we still need. The era commons id is actually a prop on the user now - this is relatively old code.

2022-07-21 13:24 UTC, rushtong commented
> i believe that i removed all usages of deprecated user properties EXCEPT for the usages on the dar application page; I can go ahead and do that, too, but I wasn't sure if that was in the scope of this PR.

I'm pretty sure we've already dealt with the DAR application page in previous stories, no need to look further there.

2022-07-21 13:28 UTC, rushtong requested changes
One small un-delete/update and I think this is ready to go!

2022-07-21 16:24 UTC, rushtong approved these changes
This looks good to go 👍🏽

2022-07-22 15:35 UTC, quazi-broad approved these changes
Changes look good to me and I did not encounter any issues with the UI when running against the consent changes in a local instance.

2022-07-22 15:44 UTC, merged