[DUOS-2723] Update Policy Pages
DataBiosphere/duos-ui pull request #2366
Opened 2023-10-24 13:41 UTC by hams7504

### Addresses
https://broadworkbench.atlassian.net/browse/DUOS-2723

### Summary

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2023-10-24 18:04 UTC, rushtong approved these changes
👍🏽

2023-10-24 19:18 UTC, fboulnois requested changes
lgtm, one recommendation:

2023-10-24 19:18 UTC, fboulnois commented on src/pages/DMSPolicyInfo.jsx
> +                    <p><b>DUOS</b> can register open-access and controlled-access datasets, regardless of the storage locationn, or if the DAC received
```suggestion
                    <p><b>DUOS</b> can register open-access and controlled-access datasets, regardless of the storage location, or if the DAC received
```

2023-10-25 14:04 UTC, hams7504 commented on src/pages/DMSPolicyInfo.jsx
> +                    <p><b>DUOS</b> can register open-access and controlled-access datasets, regardless of the storage locationn, or if the DAC received
Thanks for catching that!

2023-10-26 13:50 UTC, fboulnois approved these changes
👍

2023-10-26 17:10 UTC, merged