[DUOS-2825] Replace institution id with name in /datalibrary/myinstitution page
DataBiosphere/duos-ui pull request #2416
Opened 2023-12-04 18:55 UTC by hams7504

### Addresses
https://broadworkbench.atlassian.net/browse/DUOS-2825

### Summary
<img width="1512" alt="Screenshot 2023-12-04 at 1 55 28 PM" src="https://github.com/DataBiosphere/duos-ui/assets/36281103/5809fcad-5348-4f94-b0a5-eb09dfa067a7">

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2023-12-04 19:10 UTC, rushtong commented on src/pages/DatasetSearch.js
> +        setInstitutionName(res.name);
It would be nice to have some error handling here ... if `res` comes back as not found, we could see an undefined error on `res.name`

2023-12-04 19:15 UTC, rushtong commented on src/pages/DatasetSearch.js
> +        setInstitutionName(res.name);
Another question ... I think we have this value on the user already as part of the `/api/user/me` API call which should also be stored in `Storage.getCurrentUser()`. Why do we need to query for this value again here?

2023-12-04 20:15 UTC, fboulnois requested changes
See comment below:

2023-12-04 20:15 UTC, fboulnois commented on src/pages/DatasetSearch.js
> +        setInstitutionName(res.name);
I don't think we need to `useState` either. The bug can be fixed by setting `const institution = user.institution` and then extracting the `institution?.name` and `institution?.id`.

2023-12-05 17:58 UTC, fboulnois approved these changes
👍

2023-12-05 17:59 UTC, fboulnois commented on src/pages/DatasetSearch.js
>    const institution = user.institution?.id;
Maybe switch this to `institutionId` for consistency and correctness

2023-12-06 15:16 UTC, rushtong approved these changes
👍🏽

2023-12-06 18:20 UTC, merged