[DT-779] Clear selected filters code
DataBiosphere/duos-ui pull request #2725
Opened 2024-11-14 15:59 UTC by s-rubenstein

### Addresses
Adds a clear filters button

### Summary

https://github.com/user-attachments/assets/52904ca1-8b6e-43ba-b4fd-5a4cc84104ac

----
Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2024-11-14 16:26 UTC, rushtong commented
I think this interferes with the search bar. If I enter a value there and clear the search, the dataset list remains unchanged.

2024-11-14 16:46 UTC, s-rubenstein commented
Good call! Clear search definitely seems affected. I'll poke around

2024-11-14 19:48 UTC, rushtong approved these changes
Looks reasonable 👍🏽

2024-11-14 19:48 UTC, rushtong commented on src/components/data_search/DatasetFilterList.jsx
> +import { Button, Typography } from '@mui/material'
nit: missing semicolon

2024-11-14 20:33 UTC, fboulnois requested changes
The search no longer works as expected:

1. Enter a keyword like "All"
2. Clicking "Clear Search" has no effect
3. Manually removing the search text has no effect

2024-11-14 20:43 UTC, s-rubenstein commented
@fboulnois that is not what I see on my local - maybe we can verify we are running the same version?

2024-11-14 20:46 UTC, s-rubenstein commented
https://github.com/user-attachments/assets/316aaecf-8fbe-4eec-a649-27a381009b78

2024-11-15 14:47 UTC, fboulnois approved these changes
👍

2024-11-15 15:53 UTC, merged