[no jira] Adding Machine Readable Consent info to about page
DataBiosphere/duos-ui pull request #399
Opened 2020-04-10 21:55 UTC by solideoglori

Unsure of correctness of PR. I believe lines 63-72 and the machine-readable-consent-forms.png should be the only new lines compared to what is currently on dev/stag/prod. Not sure why others lines and files are appearing as new.

2020-04-10 21:57 UTC, solideoglori commented
Aiming for this: 

![image](https://user-images.githubusercontent.com/52168754/79025753-a8578a00-7b54-11ea-8fff-a83968e7e9b3.png)

2020-04-12 09:50 UTC, rushtong requested changes
These files exist in your local install, but do not exist in github:
* public/DUOS_LibraryCardAgreementTemplate_3.28.20.pdf 
* public/images/DUOS_LC_Process.PNG 
* public/images/LC_only_process.PNG

Note that there are lower cased versions of the images here: https://github.com/DataBiosphere/duos-ui/tree/develop/public/images so I think the root issue has to do with different cased file names and possibly a windows platform issue. If you can try to stick to lower cased file names, it should help prevent this in the future. Until you remove them and check out a new copy of develop, they will be considered new files.

Also see inline comment about spaces in file names.

Outside of that, the content looks good.

2020-04-12 09:50 UTC, rushtong commented on src/pages/HomeAbout.js
> +                  img({ src: "/images/machine readable consent forms.png", className: "col-lg-12 col-md-12 col-sm-12 col-xs-12 home-content-graphic", alt: "About icon" }),
Avoid spaces in file names:
```suggestion
                  img({ src: "/images/machine_readable_consent_forms.png", className: "col-lg-12 col-md-12 col-sm-12 col-xs-12 home-content-graphic", alt: "About icon" }),
```

2020-04-14 17:38 UTC, solideoglori commented
I updated the code to reference the existing lower case doc and images, and accepted the spacing fix. Is there a way to delete the doc and images I committed in GH before merging?

2020-04-14 17:52 UTC, rushtong commented
@solideoglori 
```
git rm public/DUOS_LibraryCardAgreementTemplate_3.28.20.pdf
git commit -m 'removing unused file' .
```
Lather, rinse, repeat for each file you don't want. Then ... 
```
git push origin HomeAbout_SO_LCDAA_Updates
```

2020-04-14 17:54 UTC, rushtong commented
Looks like there's a conflict between your version of `HomeAbout.js` and the latest version from develop. One way to fix that is to save your changes locally, checkout the version from develop, then re-apply your local changes.
![Screen Shot 2020-04-14 at 1 54 23 PM](https://user-images.githubusercontent.com/116679/79257322-777a9c00-7e57-11ea-9e21-3b1a340944ca.png)

2020-04-16 15:03 UTC, closed without merging