[DUOS-668][risk=no] Remove the Manage Ontologies and Add Ontologies p…
DataBiosphere/duos-ui pull request #475
Opened 2020-06-02 16:27 UTC by Marianie-Simeon

-Remove ManageOntologies.js and AddOntologiesModal.js
-Remove lines containing OntologiesModal from AdminConsoleBox.css, AdminConsole.js, Routes.js

2020-06-02 16:28 UTC, Marianie-Alphonse reviewed
Should I edit the Ajax file?

2020-06-02 16:38 UTC, rushtong commented
@Marianie-Simeon 

> Should I edit the Ajax file?

Yes, please do. I think it's just:
* Files.getOntologyFile
* Ontology.postOntologyFile
* Ontology.retrieveIndexedFiles
* Ontology.deleteOntologyFile
* Ontology.getOntologyTypes

But please do find usages to ensure that.

2020-06-02 18:02 UTC, Marianie-Simeon commented
I just updated the ajax.js

2020-06-02 19:06 UTC, rushtong requested changes
Need a couple of reverts (see comments inline) but otherwise looks good.

2020-06-02 19:06 UTC, rushtong commented on src/libs/ajax.js
> -  translateDataUse: async dataUse => {
This method in use elsewhere, please revert this deletion.

2020-06-02 19:06 UTC, rushtong commented on src/libs/ajax.js
> -  getAutoCompleteOT: async partial => {
This method in use elsewhere, please revert this deletion.

2020-06-02 21:07 UTC, Marianie-Simeon commented
It should be updated now

2020-06-03 10:51 UTC, rushtong approved these changes
👍  Thank you!

2020-06-03 15:39 UTC, merged