DUOS-678 Add/remove collaborators (lab/internal) [rel=no]
DataBiosphere/duos-ui pull request #568
Opened 2020-08-25 12:40 UTC by JVThomas

PR addresses [DUOS-678](https://broadinstitute.atlassian.net/browse/DUOS-678) regarding the addition of a collaborator list for both lab members and internal collaborators for Step 1. The code adds a new component to handle the add/remove functionality alongside code refactors of helper methods to remove redundant actions. Error validation will be added as part of a separate PR and has merged in the variable changes for step 3 attributes. Code also introduces uuid package to generate uuids for collaborator list items for front-end rendering via v4 algorithm (random).

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] PR is labeled with a Jira ticket number and includes a link to the ticket
- [x] PR is labeled with a security risk modifier [no, low, medium, high] 
- [x] PR describes scope of changes

In all cases:

- [ ] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [ ] Get PO sign-off for all non-trivial UI or workflow changes
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2020-08-25 18:23 UTC, rushtong requested changes
Some minor codacy issues listed here: https://app.codacy.com/gh/DataBiosphere/duos-ui/pullRequest?prid=6068073
Code looks good, functions great. 
See minor change requests inline.

2020-08-25 18:23 UTC, rushtong commented on src/pages/dar_application/CollaboratorList.js
> +    margin: "2px",
Optional. As a side note, if you use raw integers here, it defaults to px. This should have the same effect.
```suggestion
    margin: 2,
```
But, we should use single quotes if we do use strings.

2020-08-25 18:23 UTC, rushtong commented on src/pages/dar_application/CollaboratorList.js
> +    margin: "2px"
nit: single quotes

2020-08-25 18:23 UTC, rushtong commented on src/pages/dar_application/CollaboratorList.js
> +  };
Not a request for change, but more of a TOL or opportunity for discussion. You can see how I handled the case of manipulating a state list for adding/removing users [here](https://github.com/DataBiosphere/duos-ui/blob/develop/src/pages/manage_dac/DacUsers.js). I haven't given this that much thought, but we should try to establish a standard pattern for this so we can all read each other's code more efficiently

2020-08-25 18:23 UTC, rushtong commented on src/pages/dar_application/CollaboratorList.js
> +          //Thus the YesNoRadioGroup refactor should be handled on a separate PR
Agreed on these comments ... I'm really not a fan of that component. In `VoteQuestion`, I essentially wrote my own version that's less bootstrappy and doesn't rely on the strange layered effect in `YesNoRadioGroup`. I recommend deprecating the old component and moving forward with the pattern you have here.

2020-08-25 18:23 UTC, rushtong commented on src/pages/dar_application/ResearcherInfo.js
> +    marginTop: "5rem"
nit: single quotes

2020-08-25 18:23 UTC, rushtong commented on src/pages/dar_application/CollaboratorList.js
> +          //Thus the YesNoRadioGroup refactor should be handled on a separate PR
Not for this PR, but a follow on to the YNRG conversation. If you look closely, the selection of the selected radio buttons are not perfectly centered. 
![Screen Shot 2020-08-25 at 2 20 09 PM](https://user-images.githubusercontent.com/116679/91212484-4a2fdb80-e6de-11ea-8217-495f728151fa.png)

2020-08-25 19:37 UTC, JVThomas commented on src/pages/dar_application/CollaboratorList.js
> +    margin: "2px",
I'll use single quotes. I prefer to have the units explicitly stated in case a reviewer isn't familiar with the defaults.

2020-08-27 13:15 UTC, rushtong approved these changes
Looks good 👍 One minor comment inline that should not hold up this PR.

2020-08-27 13:15 UTC, rushtong commented on src/pages/dar_application/CollaboratorList.js
> -          //Thus the YesNoRadioGroup refactor should be handled on a separate PR
nit: I don't think we need these comments if we have a story for the YNRG refactor.

2020-09-01 12:48 UTC, merged