DUOS-1097[risk=no]User Session Timeout is not redirecting to home
DataBiosphere/duos-ui pull request #948
Opened 2021-03-17 21:04 UTC by raejohanek

Scope: 
Add timeout to UI that matches timeout on backend
~this does not work, nothing happens 

Addresses:
https://broadworkbench.atlassian.net/browse/DUOS-1097

Have you read [Terra's Contributing Guide](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] PR is labeled with a Jira ticket number and includes a link to the ticket
- [ ] PR is labeled with a security risk modifier [no, low, medium, high] 
- [ ] PR describes scope of changes

In all cases:

- [ ] Get a minimum of one thumbs worth of review, preferably 2 if enough team members are available
- [ ] Get PO sign-off for all non-trivial UI or workflow changes
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this
- [ ] Test this change deployed correctly and works on dev environment after deployment

2021-03-18 18:34 UTC, raejohanek commented on src/components/SignIn.js
> +  };
address compilation warnings

2021-03-19 11:56 UTC, JVThomas requested changes
You shouldn't have to change any of the axios methods at all for this fix. The only component you need to change is ```AuthenticatedRoute.js```, especially now that the backend has a ```/me``` endpoint that you can use as a safe way to check for active sessions.

The idea is to redirect before the component even loads. The changes here would only happen after the fact.

2021-03-19 11:58 UTC, JVThomas commented
As a starting point, look at ```Routes.js``` and ```AuthenticatedRoutes.js``` to get a high-level view of what the latter is trying to accomplish.

2021-03-19 12:19 UTC, rushtong commented
One of the effects we're seeing is that sessions are timing out after the component loads, and when the user follows a rendered link. Those cases are causing 401's that aren't getting caught.

2021-03-19 12:24 UTC, JVThomas commented
> One of the effects we're seeing is that sessions are timing out after the component loads, and when the user follows a rendered link. Those cases are causing 401's that aren't getting caught.

Oh, in that case look into axios interceptors
https://github.com/axios/axios#interceptors

2021-03-19 17:15 UTC, raejohanek commented on src/libs/ajax.js
> +  if (!res.ok && res.status === 401) {
Update fetchAny to include the same 401 check fetchOk includes

2021-03-19 19:36 UTC, JVThomas requested changes

2021-03-19 19:36 UTC, JVThomas commented on src/libs/ajax.js
> +  if (error.status === 401) {
To get the status on an error, you'll need to do ```error.response.status```

2021-03-19 19:40 UTC, JVThomas commented on src/libs/ajax.js
> +  if (error.status === 401) {
It's specific to axios, which is probably why you don't handle errors the same way with fetchOK and fetchAny.

2021-03-19 20:05 UTC, JVThomas approved these changes
Code looks good. This should cover instances where consent requests happen after a component has loaded and after a user session has timed out.

2021-03-19 20:09 UTC, merged